### ISSUE TITLE
[Support] Type Query on dependencies

### ISSUE THREAD

**Issue by gjroelofs** [SpoonLabs/spoon-maven-plugin#35]
Following our discussion on twitter: Is it possible to query all Types which inherit from a given type within a CompilationUnit?

My primary use case is such that I need to perform code generation given all types that inherit from a given Type (E.g.: Component -> TransactionComponent) in an Entity model. These either exists within the source code, or in the binary dependencies. These types need not be altered, but I do need to query information on them. (variables, constructors and such)

Using Query.getReferences only those references which are directly used by the source code are returned.
If I use factory.Type.createReference() I get a CtTypeReference to the type in question (even those in the dependencies) and can properly query for all required attributes. My problem however is that I need to discover all without knowing their type before hand.

**Comment by GerardPaligot** [comment]
Hi @gjroelofs,

Sorry for the delay but I wanted to inform myself on the subject before. Well, the main goal of Spoon isn't to scan all types of all dependencies of the target project. 

*Crap, Spoon sucks!*.

The only way to get all types of all dependencies of your project is to add all sources in your source classpath and apply spoon on them. Spoon needs sources to get their information and to manipulate them.

*Wow, maybe, Spoon can rock!*

:)

**Comment by gjroelofs** [comment]
I'm certainly not saying Spoon isn't a very good tool!

*(Although I could use some more examples with regards to templated code generation. The FAQ mentions "Generative Programming with Spoon" but doesn't link to it, nor can I find it anywhere.)*

However, in our use case the API will be consumed by third-parties in situations where I cannot guarantee access to the source. Up until now we've used Xtend & Reflections to analyze the compilation unit. 

I wanted to replace this with Spoon so we could use it in Java.
My plan of attack will now be to use Reflections for the dependencies, and Spoon for the sources.

**Comment by GerardPaligot** [comment]
> My plan of attack will now be to use Reflections for the dependencies, and Spoon for the sources.

That sounds like a good plan because Spoon isn't suitable for the analyse of dependencies. If you have some bugs with Spoon, don't hesitate to report them on the main repository [here](https://github.com/INRIA/spoon).

> (Although I could use some more examples with regards to templated code generation. The FAQ mentions "Generative Programming with Spoon" but doesn't link to it, nor can I find it anywhere.)

Currently, we are working on a complete documentation of Spoon. FAQ is soon a bad memory. :)

**Comment by gjroelofs** [comment]
Fair enough; I'll eagerly await these then. :-)

As a final small Q: Is it possible to access the model Spoon builds, even if the source does not fully compile?

**Comment by GerardPaligot** [comment]
The source code don't compile because there are syntax errors or because you use some classes without their declaration?

For the first case, it isn't possible. Spoon builds its AST from JDT, the eclipse compiler. If the Java source isn't valid, JDT can't give at Spoon information to build the AST.

For the second, you can use the "noclasspath" mode.
